# 配置的项目名称
server.context-path: /TelemetryServer

# 引入日志配置文件
logging:
  config:
    classpath: logback.xml

# mongodb数据库配置
spring:
  data:
    mongodb:
      host: 116.196.91.10
      port: 27017
      database: mongodb
      username: mongodb
      password: passw0rd

# 监控端口号配置
# management.server.port: 8083
# management.endpoints.web.exposure.include: *